# Generated by Django 4.2.5 on 2023-10-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('completions', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('sacks', models.IntegerField()),
                ('sack_yards', models.IntegerField()),
                ('sack_fumbles', models.IntegerField()),
                ('sack_fumbles_lost', models.IntegerField()),
                ('passing_air_yards', models.IntegerField()),
                ('passing_yards_after_catch', models.IntegerField()),
                ('passing_first_downs', models.IntegerField()),
                ('passing_2pt_conversions', models.IntegerField()),
                ('carries', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('rushing_fumbles', models.IntegerField()),
                ('rushing_fumbles_lost', models.IntegerField()),
                ('rushing_2pt_conversions', models.IntegerField()),
                ('rushing_first_downs', models.IntegerField()),
                ('receptions', models.IntegerField(null=True)),
                ('targets', models.IntegerField(null=True)),
                ('receiving_yards', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('receiving_fumbles', models.IntegerField()),
                ('receiving_fumbles_lost', models.IntegerField()),
                ('receiving_yards_after_catch', models.IntegerField()),
                ('receiving_first_downs', models.IntegerField()),
                ('receiving_2pt_conversions', models.IntegerField()),
                ('receiving_target_share', models.FloatField(blank=True, null=True)),
                ('special_teams_tds', models.IntegerField()),
                ('gsis_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_stats', to='players.playeridentifier')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_stats_team', to='teams.teams')),
                ('opponent_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_stats_opponent', to='teams.teams')),
            ],
            options={
                'verbose_name_plural': 'Player Stats',
                'db_table': 'PlayerStats',
            },
        ),
    ]
