# Generated by Django 4.2.5 on 2023-10-29 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_teamstats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teamstats",
            name="receiving_target_share",
        ),
    ]
