import pandas as pd


play_by_play_times = ["drive_time_of_possession"]
play_by_play_mapper = {
    "game_id": {"dtype": "string"},
    "home_team": {"name": "home_team_id", "dtype": "string"},
    "away_team": {"name": "away_team_id", "dtype": "string"},
    "week": {"dtype": pd.Int8Dtype()},
    "posteam": {"name": "team_with_possession_id", "dtype": "string"},
    "side_of_field": {"dtype": "string"},
    "yardline_100": {"dtype": pd.Int8Dtype()},
    "quarter_seconds_remaining": {"dtype": pd.Int16Dtype()},
    "half_seconds_remaining": {"dtype": pd.Int16Dtype()},
    "game_seconds_remaining": {"dtype": pd.Int16Dtype()},
    "game_half": {"name": "half", "dtype": "string"},
    "quarter_end": {"dtype": pd.Int8Dtype()},
    "drive": {"name": "drive_num", "dtype": pd.Int8Dtype()},
    "qtr": {"name": "quarter", "dtype": pd.Int8Dtype()},
    "down": {"dtype": pd.Int8Dtype()},
    "ydstogo": {"name": "yards_to_go", "dtype": pd.Int8Dtype()},
    "ydsnet": {"name": "drive_net_yards", "dtype": pd.Int8Dtype()},
    "desc": {"name": "play_description", "dtype": "string"},
    "play_type": {"dtype": "string"},
    "yards_gained": {"dtype": pd.Int8Dtype()},
    "shotgun": {"dtype": pd.BooleanDtype()},
    "no_huddle": {"dtype": pd.BooleanDtype()},
    "qb_dropback": {"dtype": pd.BooleanDtype()},
    "qb_kneel": {"dtype": pd.BooleanDtype()},
    "qb_spike": {"dtype": pd.BooleanDtype()},
    "qb_scramble": {"dtype": pd.BooleanDtype()},
    "pass_length": {"dtype": "string"},
    "pass_location": {"dtype": "string"},
    "air_yards": {"name": "pass_air_yards", "dtype": pd.Int8Dtype()},
    "yards_after_catch": {"name": "pass_yards_after_catch", "dtype": pd.Int8Dtype()},
    "run_location": {"name": "rush_location", "dtype": "string"},
    "run_gap": {"name": "rush_gap", "dtype": "string"},
    "field_goal_result": {"dtype": "string"},
    "kick_distance": {"name": "field_goal_kick_distance", "dtype": pd.Int8Dtype()},
    "extra_point_attempt": {"dtype": pd.BooleanDtype()},
    "extra_point_result": {"dtype": "string"},
    "field_goal_attempt": {"dtype": pd.BooleanDtype()},
    "two_point_attempt": {"dtype": pd.BooleanDtype()},
    "kickoff_attempt": {"dtype": pd.BooleanDtype()},
    "punt_attempt": {"dtype": pd.BooleanDtype()},
    "timeout": {"name": "timeout_taken", "dtype": pd.BooleanDtype()},
    "timeout_team": {"name": "timeout_team_id", "dtype": "string"},
    "td_team": {"name": "touchdown_team_id", "dtype": "string"},
    "td_player_id": {"name": "touchdown_gsis_id", "dtype": "string"},
    "total_home_score": {"name": "home_team_score", "dtype": pd.Int8Dtype()},
    "total_away_score": {"name": "away_team_score", "dtype": pd.Int8Dtype()},
    "punt_blocked": {"dtype": pd.BooleanDtype()},
    "first_down_rush": {"name": "rush_first_down", "dtype": pd.BooleanDtype()},
    "first_down_pass": {"name": "pass_first_down", "dtype": pd.BooleanDtype()},
    "third_down_converted": {"dtype": pd.BooleanDtype()},
    "third_down_failed": {"dtype": pd.BooleanDtype()},
    "fourth_down_converted": {"dtype": pd.BooleanDtype()},
    "fourth_down_failed": {"dtype": pd.BooleanDtype()},
    "incomplete_pass": {"name": "pass_incomplete", "dtype": pd.BooleanDtype()},
    "complete_pass": {"name": "pass_complete", "dtype": pd.BooleanDtype()},
    "touchback": {"name": "kickoff_touchback", "dtype": pd.BooleanDtype()},
    "kickoff_inside_twenty": {"dtype": pd.BooleanDtype()},
    "kickoff_in_endzone": {"dtype": pd.BooleanDtype()},
    "kickoff_out_of_bounds": {"dtype": pd.BooleanDtype()},
    "kickoff_downed": {"dtype": pd.BooleanDtype()},
    "kickoff_fair_catch": {"dtype": pd.BooleanDtype()},
    "interception": {"name": "pass_interception", "dtype": pd.BooleanDtype()},
    "punt_inside_twenty": {"dtype": pd.BooleanDtype()},
    "punt_in_endzone": {"dtype": pd.BooleanDtype()},
    "punt_out_of_bounds": {"dtype": pd.BooleanDtype()},
    "punt_downed": {"dtype": pd.BooleanDtype()},
    "punt_fair_catch": {"dtype": pd.BooleanDtype()},
    "fumble_forced": {"dtype": pd.BooleanDtype()},
    "fumble_not_forced": {"dtype": pd.BooleanDtype()},
    "fumble_out_of_bounds": {"dtype": pd.BooleanDtype()},
    "fumble_lost": {"dtype": pd.BooleanDtype()},
    "fumble": {"dtype": pd.BooleanDtype()},
    "fumbled_1_player_id": {"name": "fumbled_gsis_id", "dtype": "string"},
    "solo_tackle": {"name": "tackle_solo", "dtype": pd.BooleanDtype()},
    "assist_tackle": {"name": "tackle_assist", "dtype": pd.BooleanDtype()},
    "tackled_for_loss": {"dtype": pd.BooleanDtype()},
    "own_kickoff_recovery": {"dtype": pd.BooleanDtype()},
    "own_kickoff_recovery_td": {
        "name": "own_kickoff_recovery_touchdown",
        "dtype": pd.BooleanDtype(),
    },
    "rush_attempt": {"dtype": pd.BooleanDtype()},
    "pass_attempt": {"dtype": pd.BooleanDtype()},
    "sack": {"dtype": pd.BooleanDtype()},
    "touchdown": {"dtype": pd.BooleanDtype()},
    "pass_touchdown": {"dtype": pd.BooleanDtype()},
    "rush_touchdown": {"dtype": pd.BooleanDtype()},
    "return_touchdown": {"dtype": pd.BooleanDtype()},
    "complete_pass": {"name": "pass_complete", "dtype": pd.BooleanDtype()},
    "passer_player_id": {"name": "passer_gsis_id", "dtype": "string"},
    "passing_yards": {"name": "pass_yards", "dtype": pd.Int8Dtype()},
    "receiver_player_id": {"name": "receiver_gsis_id", "dtype": "string"},
    "rusher_player_id": {"name": "rusher_gsis_id", "dtype": "string"},
    "rushing_yards": {"name": "rush_yards", "dtype": pd.Int8Dtype()},
    "kicker_player_id": {"name": "kicker_gsis_id", "dtype": "string"},
    "penalty_player_id": {"name": "penalty_gsis_id", "dtype": "string"},
    "penalty_team": {"name": "penalty_team_id", "dtype": "string"},
    "penalty_yards": {"dtype": pd.Int8Dtype()},
    "penalty_type": {"dtype": "string"},
    "fixed_drive_result": {"name": "drive_result", "dtype": "string"},
    "drive_inside20": {"name": "drive_inside_twenty", "dtype": pd.BooleanDtype()},
    "drive_play_count": {"dtype": pd.Int8Dtype()},
    "drive_first_downs": {"dtype": pd.Int8Dtype()},
    "drive_ended_with_score": {"dtype": pd.BooleanDtype()},
    "drive_quarter_start": {"dtype": pd.Int8Dtype()},
    "drive_quarter_end": {"dtype": pd.Int8Dtype()},
    "drive_yards_penalized": {"dtype": pd.Int8Dtype()},
    "drive_start_transition": {"dtype": "string"},
    "drive_end_transition": {"dtype": "string"},
    "offense_formation": {"dtype": "string"},
    "offense_personnel": {"dtype": "string"},
    "defenders_in_box": {"dtype": pd.Int8Dtype()},
    "defense_personnel": {"dtype": "string"},
    "number_of_pass_rushers": {
        "name": "defense_num_of_rushers",
        "dtype": pd.Int8Dtype(),
    },
    "offense_players": {"name": "offense_player_gsis_ids", "dtype": "string"},
    "defense_players": {"name": "defense_player_gsis_ids", "dtype": "string"},
}
