play_by_play_mapper = {
    "home_team": "home_team_id",
    "away_team": "away_team_id",
    "posteam": "team_with_possession",
    "drive": "drive_num",
    "qtr": "quarter",
    "ydstogo": "yards_to_go",
    "ydsnet": "drive_net_yards",
    "desc": "play_description",
    "air_yards": "pass_air_yards",
    "yards_after_catch": "pass_yards_after_catch",
    "timeout": "timeout_taken",
    "td_team": "touchdown_team",
    "td_player_id": "touchdown_gsis_id",
    "total_home_score": "home_team_score",
    "total_away_score": "away_team_score",
    "first_down_rush": "rush_first_down",
    "first_down_pass": "pass_first_down",
    "incomplete_pass": "pass_incomplete",
    "touchback": "kickoff_touchback",
    "interception": "pass_interception",
    "solo_tackle": "tackle_solo",
    "assist_tackle": "tackle_assist",
}