# Generated by Django 4.2.5 on 2023-10-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayByPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PlayByPlay",
                "db_table": "PlayByPlay",
            },
        ),
        migrations.CreateModel(
            name="Stadiums",
            fields=[
                (
                    "stadium_id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("surface", models.CharField(default="", max_length=10)),
                ("roof", models.CharField(default="", max_length=8)),
            ],
            options={
                "db_table": "Stadiums",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "game",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("season", models.IntegerField(editable=False)),
                ("game_type", models.CharField(editable=False, max_length=4)),
                ("week", models.IntegerField(editable=False)),
                ("gameday", models.DateField(editable=False)),
                ("weekday", models.CharField(editable=False, max_length=9)),
                ("gametime", models.TimeField(editable=False)),
                ("location", models.CharField(editable=False, max_length=4)),
                ("overtime", models.IntegerField(editable=False)),
                (
                    "espn",
                    models.IntegerField(
                        db_column="espn_game_id",
                        editable=False,
                        verbose_name="espn_game_id",
                    ),
                ),
                (
                    "div_game",
                    models.IntegerField(
                        db_column="divisional_game",
                        editable=False,
                        verbose_name="divisional_game",
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="schedule_away",
                        to="teams.teams",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="schedule_home",
                        to="teams.teams",
                    ),
                ),
                (
                    "stadium_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="games.stadiums",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Schedule",
                "db_table": "Schedules",
            },
        ),
    ]
