# Generated by Django 4.2.5 on 2023-10-02 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stadiums",
            new_name="Stadium",
        ),
    ]
