# Generated by Django 4.2.5 on 2023-10-02 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_rename_stadiums_stadium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="game",
            new_name="game_id",
        ),
    ]
