# Generated by Django 4.2.5 on 2023-10-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_rename_game_schedule_game_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stadium",
            name="roof",
        ),
        migrations.RemoveField(
            model_name="stadium",
            name="surface",
        ),
        migrations.AddField(
            model_name="schedule",
            name="roof",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="schedule",
            name="surface",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="stadium",
            name="name",
            field=models.CharField(default="", max_length=70, verbose_name="name"),
        ),
    ]
