# Generated by Django 4.2.5 on 2023-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_remove_stadium_roof_remove_stadium_surface_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stadium",
            name="stadium_id",
            field=models.CharField(
                editable=False, max_length=7, primary_key=True, serialize=False
            ),
        ),
    ]
