# Generated by Django 4.2.5 on 2023-10-02 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0005_alter_stadium_stadium_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="espn",
            new_name="espn_game_id",
        ),
    ]
