# Generated by Django 4.2.5 on 2023-10-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_rename_espn_schedule_espn_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="overtime",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
