# Generated by Django 4.2.5 on 2023-10-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("games", "0009_alter_schedule_overtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="away_team",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="schedule_away",
                to="teams.teams",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="home_team",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="schedule_home",
                to="teams.teams",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="stadium_id",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.RESTRICT,
                to="games.stadium",
            ),
        ),
    ]
