# Generated by Django 4.2.5 on 2023-10-07 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "games",
            "0001_squashed_0010_alter_schedule_away_team_alter_schedule_home_team_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="div_game",
            new_name="divisional_game",
        ),
    ]
