# Generated by Django 4.2.5 on 2023-10-11 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_team_abbr_teams_team"),
        ("players", "0011_alter_playeridentifier_options_and_more"),
        ("games", "0011_rename_div_game_schedule_divisional_game"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playbyplay",
            options={"verbose_name_plural": "Play By Play"},
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="away_team",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_away_team",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="away_team_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="away_timeouts_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="defenders_in_box",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="defense_num_of_rushers",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="defense_personnel",
            field=models.CharField(default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="defense_player_gsis_ids",
            field=models.CharField(default="", max_length=175),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="down",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_end_transition",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_ended_with_score",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_first_downs",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_inside_twenty",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_net_yards",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_num",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_play_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_quarter_end",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_quarter_start",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_result",
            field=models.CharField(default="", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_start_transition",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_time_of_possession",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="drive_yards_penalized",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="extra_point_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="extra_point_result",
            field=models.CharField(default="", max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="field_goal_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="field_goal_kick_distance",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="field_goal_result",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fourth_down_converted",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fourth_down_failed",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumble",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumble_forced",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumble_lost",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumble_not_forced",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumble_out_of_bounds",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="fumbled_player_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_fumbler",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="game_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_game_ids",
                to="games.schedule",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="game_seconds_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="half",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="half_seconds_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="home_team",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_home_team",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="home_team_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="home_timeouts_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kicker_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_kicking_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_downed",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_fair_catch",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_in_endzone",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_inside_twenty",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_out_of_bounds",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="kickoff_touchback",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="no_huddle",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="offense_formation",
            field=models.CharField(default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="offense_personnel",
            field=models.CharField(default="", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="offense_player_gsis_ids",
            field=models.CharField(default="", max_length=175),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="own_kickoff_recovery",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="own_kickoff_recovery_touchdown",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_air_yards",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_complete",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_first_down",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_incomplete",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_interception",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_length",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_location",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_touchdown",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_yards",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="pass_yards_after_catch",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="passer_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_passing_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="penalty",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="penalty_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_penalty_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="penalty_team",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_penalty_team",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="penalty_type",
            field=models.CharField(default="", max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="penalty_yards",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="play_description",
            field=models.CharField(
                db_column="play_description", default="", max_length=750
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="play_type",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_blocked",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_downed",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_fair_catch",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_in_endzone",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_inside_twenty",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="punt_out_of_bounds",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="qb_dropback",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="qb_hit",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="qb_kneel",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="qb_scramble",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="qb_spike",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="quarter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="quarter_end",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="quarter_seconds_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="receiver_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_receiving_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="return_touchdown",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="run_gap",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="run_location",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="run_touchdown",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="rush_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="rush_first_down",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="rush_yards",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="rusher_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_rushing_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="sack",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="safety",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="shotgun",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="side_of_field",
            field=models.CharField(default="", max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="tackle_assist",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="tackle_solo",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="tackled_for_loss",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="team_with_possession",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_team_with_possession",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="third_down_converted",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="third_down_failed",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="timeout_taken",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="timeout_team",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_timeout_team",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="touchdown",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="touchdown_gsis_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_touchdown_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="touchdown_team",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_touchdown_team",
                to="teams.teams",
            ),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="two_point_attempt",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="two_point_conv_result",
            field=models.CharField(default="", max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="week",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="yardline_100",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="yards_gained",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="playbyplay",
            name="yards_to_go",
            field=models.IntegerField(default=0),
        ),
    ]
