# Generated by Django 4.2.5 on 2023-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0013_rename_run_gap_playbyplay_rush_gap_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="drive_time_of_possession",
            field=models.TimeField(),
        ),
    ]
