# Generated by Django 4.2.5 on 2023-10-11 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0014_alter_playbyplay_drive_time_of_possession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="defense_player_gsis_ids",
            field=models.CharField(default="", max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="drive_time_of_possession",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="offense_player_gsis_ids",
            field=models.CharField(default="", max_length=175, null=True),
        ),
    ]
