# Generated by Django 4.2.5 on 2023-10-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0015_alter_playbyplay_defense_player_gsis_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="drive_end_transition",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="drive_start_transition",
            field=models.CharField(default="", max_length=30, null=True),
        ),
    ]
