# Generated by Django 4.2.5 on 2023-10-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0016_alter_playbyplay_drive_end_transition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="drive_num",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
