# Generated by Django 4.2.5 on 2023-10-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_team_abbr_teams_team"),
        ("games", "0017_alter_playbyplay_drive_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="team_with_possession",
            field=models.ForeignKey(
                db_column="team_with_possession_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_team_with_possession",
                to="teams.teams",
            ),
        ),
    ]
