# Generated by Django 4.2.5 on 2023-10-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0011_alter_playeridentifier_options_and_more"),
        ("teams", "0002_rename_team_abbr_teams_team"),
        ("games", "0018_alter_playbyplay_team_with_possession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playbyplay",
            name="fumbled_gsis",
            field=models.ForeignKey(
                db_column="fumbled_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_fumbler",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="kicker_gsis",
            field=models.ForeignKey(
                db_column="kicker_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_kicking_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="passer_gsis",
            field=models.ForeignKey(
                db_column="passet_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_passing_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="penalty_gsis",
            field=models.ForeignKey(
                db_column="penalty_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_penalty_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="penalty_team",
            field=models.ForeignKey(
                db_column="penalty_team_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_penalty_team",
                to="teams.teams",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="receiver_gsis",
            field=models.ForeignKey(
                db_column="receiver_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_receiving_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="rusher_gsis",
            field=models.ForeignKey(
                db_column="rusher_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_rushing_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="timeout_team",
            field=models.ForeignKey(
                db_column="timeout_team_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_timeout_team",
                to="teams.teams",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="touchdown_gsis",
            field=models.ForeignKey(
                db_column="touchdown_gsis_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_touchdown_player",
                to="players.playeridentifier",
            ),
        ),
        migrations.AlterField(
            model_name="playbyplay",
            name="touchdown_team",
            field=models.ForeignKey(
                db_column="touchdown_team_id",
                default="",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="pbp_touchdown_team",
                to="teams.teams",
            ),
        ),
    ]
