# Generated by Django 4.2.5 on 2023-10-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0019_alter_playbyplay_fumbled_gsis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playbyplay",
            name="season",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
