# Generated by Django 4.2.5 on 2023-10-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='PlayerIdentifier',
            fields=[
                ('gsis_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('espn_id', models.IntegerField(null=True)),
                ('yahoo_id', models.IntegerField(null=True)),
                ('db_season', models.IntegerField(null=True)),
                ('age', models.FloatField(null=True)),
                ('college', models.CharField(max_length=30, null=True)),
                ('headshot', models.CharField(default='', max_length=255)),
                ('player_name', models.CharField(db_column='player_name', default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Player Identifiers',
                'db_table': 'PlayerIdentifiers',
            },
        ),
        migrations.CreateModel(
            name='DepthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('formation', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=4)),
                ('depth_position', models.CharField(blank=True, max_length=4)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_depth', to='teams.teams')),
                ('gsis_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_depth', to='players.playeridentifier')),
            ],
            options={
                'verbose_name_plural': 'Depth Charts',
                'db_table': 'DepthCharts',
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('status', models.CharField(max_length=5)),
                ('week', models.IntegerField()),
                ('gsis_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='player_roster', to='players.playeridentifier')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_roster', to='teams.teams')),
            ],
            options={
                'verbose_name_plural': 'Rosters',
                'db_table': 'Rosters',
            },
        ),
    ]
