# Generated by Django 4.2.5 on 2023-10-02 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerIdentifier",
            fields=[
                (
                    "gsis_id",
                    models.CharField(
                        db_column="player_id",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("espn_id", models.IntegerField(unique=True)),
                ("yahoo_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Identifiers",
                "db_table": "PlayerIdentifiers",
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("position", models.CharField(max_length=4)),
                ("status", models.CharField(max_length=5)),
                ("player_name", models.CharField(max_length=50)),
                ("week", models.IntegerField()),
                ("game_type", models.CharField(max_length=5)),
                ("college", models.CharField(max_length=30)),
                (
                    "player_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_roster",
                        to="players.playeridentifier",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="team_roster",
                        to="teams.teams",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rosters",
                "db_table": "Rosters",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("player_name", models.CharField(max_length=50)),
                ("headshot_url", models.CharField(max_length=255)),
                ("age", models.FloatField()),
                (
                    "player_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player",
                        to="players.playeridentifier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Players",
                "db_table": "Players",
            },
        ),
        migrations.CreateModel(
            name="DepthChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("week", models.IntegerField()),
                ("game_type", models.CharField(max_length=5)),
                ("depth_team", models.IntegerField()),
                ("formation", models.CharField(max_length=15)),
                ("jersey_number", models.IntegerField()),
                ("position", models.CharField(max_length=4)),
                ("elias_id", models.CharField(max_length=10)),
                ("depth_position", models.CharField(blank=True, max_length=4)),
                ("full_name", models.CharField(max_length=50)),
                (
                    "club_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="team_depth",
                        to="teams.teams",
                    ),
                ),
                (
                    "gsis_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_depth",
                        to="players.playeridentifier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Depth Charts",
                "db_table": "DepthCharts",
            },
        ),
    ]
