# Generated by Django 4.2.5 on 2023-10-04 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("players", "0001_initial"),
        ("players", "0002_rename_player_id_player_player_and_more"),
        ("players", "0003_rename_gsis_id_depthchart_gsis_and_more"),
        ("players", "0004_alter_playeridentifier_espn_id_and_more"),
        ("players", "0005_remove_depthchart_elias_id"),
        ("players", "0006_alter_playeridentifier_espn_id_and_more"),
        ("players", "0007_rename_player_roster_gsis"),
        ("players", "0008_roster_headshot_delete_player"),
    ]

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerIdentifier",
            fields=[
                (
                    "gsis_id",
                    models.CharField(
                        db_column="player_id",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("espn_id", models.IntegerField(null=True)),
                ("yahoo_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=50)),
                ("db_season", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name_plural": "Identifiers",
                "db_table": "PlayerIdentifiers",
            },
        ),
        migrations.CreateModel(
            name="DepthChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("week", models.IntegerField()),
                ("game_type", models.CharField(max_length=5)),
                ("depth_team", models.IntegerField()),
                ("formation", models.CharField(max_length=15)),
                ("jersey_number", models.IntegerField()),
                ("position", models.CharField(max_length=4)),
                ("depth_position", models.CharField(blank=True, max_length=4)),
                ("full_name", models.CharField(max_length=50)),
                (
                    "club_code",
                    models.ForeignKey(
                        db_column="team",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="team_depth",
                        to="teams.teams",
                        verbose_name="team",
                    ),
                ),
                (
                    "gsis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_depth",
                        to="players.playeridentifier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Depth Charts",
                "db_table": "DepthCharts",
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.IntegerField()),
                ("position", models.CharField(max_length=4)),
                ("status", models.CharField(max_length=5)),
                ("player_name", models.CharField(max_length=50)),
                ("week", models.IntegerField()),
                ("game_type", models.CharField(max_length=5)),
                ("college", models.CharField(max_length=30)),
                (
                    "gsis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="player_roster",
                        to="players.playeridentifier",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="team_roster",
                        to="teams.teams",
                    ),
                ),
                ("headshot", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name_plural": "Rosters",
                "db_table": "Rosters",
            },
        ),
    ]
