# Generated by Django 4.2.5 on 2023-10-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="player_id",
            new_name="player",
        ),
        migrations.RenameField(
            model_name="playeridentifier",
            old_name="espn_id",
            new_name="espn",
        ),
        migrations.RenameField(
            model_name="playeridentifier",
            old_name="yahoo_id",
            new_name="yahoo",
        ),
        migrations.RemoveField(
            model_name="player",
            name="player_name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="season",
        ),
        migrations.AddField(
            model_name="playeridentifier",
            name="db_season",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="depthchart",
            name="club_code",
            field=models.ForeignKey(
                db_column="team",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_depth",
                to="teams.teams",
                verbose_name="team",
            ),
        ),
        migrations.AlterField(
            model_name="playeridentifier",
            name="gsis_id",
            field=models.CharField(
                db_column="player_id",
                max_length=12,
                primary_key=True,
                serialize=False,
                verbose_name="player",
            ),
        ),
    ]
