# Generated by Django 4.2.5 on 2023-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_player_id_player_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depthchart',
            old_name='gsis_id',
            new_name='gsis',
        ),
        migrations.RenameField(
            model_name='playeridentifier',
            old_name='espn',
            new_name='espn_id',
        ),
        migrations.RenameField(
            model_name='playeridentifier',
            old_name='yahoo',
            new_name='yahoo_id',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='player_id',
            new_name='player',
        ),
        migrations.AlterField(
            model_name='playeridentifier',
            name='gsis_id',
            field=models.CharField(db_column='player_id', max_length=12, primary_key=True, serialize=False),
        ),
    ]
