# Generated by Django 4.2.5 on 2023-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_rename_gsis_id_depthchart_gsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeridentifier',
            name='espn_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playeridentifier',
            name='yahoo_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
