# Generated by Django 4.2.5 on 2023-10-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_playeridentifier_espn_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depthchart',
            name='elias_id',
        ),
    ]
