# Generated by Django 4.2.5 on 2023-10-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_remove_depthchart_elias_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeridentifier",
            name="espn_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="playeridentifier",
            name="yahoo_id",
            field=models.IntegerField(null=True),
        ),
    ]
