# Generated by Django 4.2.5 on 2023-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_remove_depthchart_elias_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depthchart",
            name="week",
        ),
        migrations.AddField(
            model_name="depthchart",
            name="week",
            field=models.ManyToManyField(to="players.roster"),
        ),
    ]
