# Generated by Django 4.2.5 on 2023-10-03 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0006_alter_playeridentifier_espn_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roster",
            old_name="player",
            new_name="gsis",
        ),
    ]
