# Generated by Django 4.2.5 on 2023-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0007_rename_player_roster_gsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="headshot",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
