# Generated by Django 4.2.5 on 2023-10-06 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_squashed_0008_roster_headshot_delete_player"),
    ]

    operations = [
        migrations.RenameField(
            model_name="depthchart",
            old_name="club_code",
            new_name="team",
        ),
    ]
