# Generated by Django 4.2.5 on 2023-10-09 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_team_abbr_teams_team"),
        ("players", "0010_rename_gsis_depthchart_gsis_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playeridentifier",
            options={"verbose_name_plural": "Player Identifiers"},
        ),
        migrations.RenameField(
            model_name="depthchart",
            old_name="depth_team",
            new_name="depth",
        ),
        migrations.RemoveField(
            model_name="depthchart",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="depthchart",
            name="jersey_number",
        ),
        migrations.RemoveField(
            model_name="playeridentifier",
            name="name",
        ),
        migrations.RemoveField(
            model_name="roster",
            name="college",
        ),
        migrations.RemoveField(
            model_name="roster",
            name="headshot",
        ),
        migrations.RemoveField(
            model_name="roster",
            name="player_name",
        ),
        migrations.RemoveField(
            model_name="roster",
            name="position",
        ),
        migrations.AddField(
            model_name="playeridentifier",
            name="age",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="playeridentifier",
            name="college",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="playeridentifier",
            name="headshot",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="playeridentifier",
            name="player_name",
            field=models.CharField(db_column="player_name", default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="depthchart",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_depth",
                to="teams.teams",
            ),
        ),
    ]
