# Generated by Django 4.2.5 on 2023-10-07 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teams",
            old_name="team_abbr",
            new_name="team",
        ),
    ]
